from sqlalchemy.orm import Session
from app.models.trial import ClinicalTrial
from app.schemas.matching import RAGQueryInput, RAGQueryResponse

class RAGTrialAssistant:
    """
    RAG Assistant for answering targeted clinical trial queries
    using retrieved trial inclusion/exclusion criteria, description, and locations.
    """

    def answer_question(self, db: Session, trial_id: str, question: str) -> RAGQueryResponse:
        trial = db.query(ClinicalTrial).filter(ClinicalTrial.id == trial_id).first()
        if not trial:
            return RAGQueryResponse(
                trial_id=trial_id,
                question=question,
                answer="Clinical trial not found in system database.",
                sources=[],
                disclaimer="System notice."
            )

        q_lower = question.lower()
        sources = [f"Clinical Trial Registry: {trial.id} - {trial.title}"]

        inclusions = [c.raw_text for c in trial.criteria if c.criterion_type == "inclusion"]
        exclusions = [c.raw_text for c in trial.criteria if c.criterion_type == "exclusion"]
        locations_list = [f"{l.facility_name or 'Site'} ({l.city or ''}, {l.country})" for l in trial.locations]

        # 1. Eligibility Requirements query
        if any(k in q_lower for k in ["eligibility", "criteria", "requirement", "qualify", "inclusive"]):
            inc_fmt = "\n".join([f"• {inc}" for inc in inclusions]) if inclusions else "• Standard protocol inclusion criteria apply."
            exc_fmt = "\n".join([f"• {exc}" for exc in exclusions]) if exclusions else "• Standard protocol exclusion criteria apply."
            
            answer = (
                f"### Official Eligibility Requirements for Trial {trial.id}\n\n"
                f"**Target Condition:** {trial.condition} | **Age Range:** {trial.min_age} - {trial.max_age} years | **Gender:** {trial.gender_requirement}\n\n"
                f"#### Key Inclusion Criteria:\n{inc_fmt}\n\n"
                f"#### Key Exclusion Criteria:\n{exc_fmt}"
            )

        # 2. Location / Available sites query
        elif any(k in q_lower for k in ["location", "where", "available", "site", "city", "country"]):
            locs_fmt = "\n".join([f"• {loc}" for loc in locations_list]) if locations_list else "• Contact sponsor for active regional clinical sites."
            answer = (
                f"### Trial Locations & Study Sites for {trial.id}\n\n"
                f"This trial is currently registered under status **{trial.status}** with sponsor **{trial.sponsor or 'Academic/Clinical Sponsor'}**.\n\n"
                f"**Active Study Sites:**\n{locs_fmt}"
            )

        # 3. Treatment / Intervention query
        elif any(k in q_lower for k in ["treatment", "drug", "intervention", "therapy", "investigative", "phase"]):
            answer = (
                f"### Investigative Treatment Details for {trial.id}\n\n"
                f"**Study Phase:** {trial.phase}\n"
                f"**Intervention / Arm:** {trial.intervention or 'Investigational agent / standard therapy comparison'}\n\n"
                f"**Study Overview:**\n{trial.brief_summary or trial.detailed_description or 'No summary provided.'}"
            )

        # 4. Score / Matching rationale query
        elif any(k in q_lower for k in ["match", "score", "why", "high", "low", "rank"]):
            answer = (
                f"### Matching Rationale for Trial {trial.id}\n\n"
                f"The AI Clinical Trial Matching engine evaluates candidates across 5 weighted dimensions:\n"
                f"1. **Hard Eligibility Rules (40%)**: Age ({trial.min_age}-{trial.max_age}), Gender ({trial.gender_requirement}), Biomarkers & Prior Treatments.\n"
                f"2. **Semantic Similarity (30%)**: NLP vector similarity between clinical notes and trial criteria text.\n"
                f"3. **Condition Alignment (15%)**: Exact/synonym match for condition **{trial.condition}**.\n"
                f"4. **Location Proximity (10%)**: Verification of available regional trial sites.\n"
                f"5. **Trial Recruitment Status (5%)**: Active recruiting status ({trial.status})."
            )

        # 5. General fallback
        else:
            answer = (
                f"### Information Summary for Clinical Trial {trial.id}\n\n"
                f"**Title:** {trial.title}\n"
                f"**Phase:** {trial.phase} | **Status:** {trial.status} | **Sponsor:** {trial.sponsor or 'N/A'}\n\n"
                f"**Brief Summary:**\n{trial.brief_summary or 'Refer to full protocol document.'}\n\n"
                f"For specific questions regarding eligibility, please ask about 'eligibility requirements', 'locations', or 'treatments'."
            )

        disclaimer = (
            "NOTICE: This response is generated by the AI RAG Clinical Trial Assistant using retrieved public protocol data. "
            "It is intended solely for decision support and research. Final clinical eligibility must be verified with trial coordinators."
        )

        return RAGQueryResponse(
            trial_id=trial_id,
            question=question,
            answer=answer,
            sources=sources,
            disclaimer=disclaimer
        )

rag_assistant = RAGTrialAssistant()
